name: Swift

on: [push]

jobs:

    macOS-swift:
        name: macOS
        runs-on: macos-14
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Xcode Version
          run: |
            sudo xcode-select -s /Applications/Xcode_15.2.app
            xcodebuild -version
            swift --version
        - name: Swift Version
          run: swift --version
        - name: Build (Debug)
          run: swift build -c debug
        - name: Build (Release)
          run: swift build -c release
