name: Swift ARM
on: [push]
jobs:

    linux-swift-arm64:
              name: Linux ARM64
              runs-on: [self-hosted, linux, ARM64]
              container:
                image: swift:5.10-jammy
              steps:
              - name: Checkout
                uses: actions/checkout@v1
              - name: Install dependencies
                run: apt update; apt install -y libavahi-compat-libdnssd-dev
              - name: Build (Release)
                run: swift build -c release
              - name: Upload build artifacts
                uses: actions/upload-artifact@v2
                with:
                  name: build-linux-arm64
                  path: ".build/aarch64-unknown-linux-gnu/release/mppsolar-homekit"
